import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { CalendarDays, ClipboardList, Flag, LayoutDashboard, Medal, Plus, Settings, Trophy, Users, FileBarChart, LogOut } from 'lucide-react';
import './style.css';

type Year={id:number,name:string,sports_start?:string,sports_end?:string,is_current:boolean}; type Event={id:number,name:string,grade_group:string,gender:string,max_teams:number,final_teams:number,project_type:string,description?:string}; type Reg={id:number,grade:string,class_name:string,leader_name:string,student_name:string,gender:string,event_id?:number,bib_number?:number};
const token=()=>localStorage.getItem('sfls_token')||'';
async function api(path:string,options:RequestInit={}){const r=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json','Authorization':'Bearer '+token(),...(options.headers||{})}});if(!r.ok)throw new Error((await r.json()).detail||'请求失败');return r.json()}
const nav=[['概览',LayoutDashboard],['学年设置',CalendarDays],['项目管理',Trophy],['班级报名',Users],['竞赛日程',ClipboardList],['项目分组',Flag],['最高记录',Medal],['秩序册生成',FileBarChart],['成绩统计',ClipboardList],['分数统计',Medal]] as const;
function Login({done}:{done:()=>void}){const [username,setUsername]=useState('admin'),[password,setPassword]=useState(''),[error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();try{const x=await api('/auth/login',{method:'POST',body:JSON.stringify({username,password})});localStorage.setItem('sfls_token',x.access_token);done()}catch(e){setError((e as Error).message)}};return <main className="login"><section><div className="mark">SFLS</div><p>苏州外国语学校</p><h1>运动会管理系统</h1><span>Sports Meet Management</span></section><form onSubmit={submit}><h2>管理员登录</h2><label>账号<input value={username} onChange={e=>setUsername(e.target.value)} /></label><label>密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="请输入密码" /></label>{error&&<div className="error">{error}</div>}<button>登录系统</button></form></main>}
function App(){const [ready,setReady]=useState(!!token()),[page,setPage]=useState('概览'),[years,setYears]=useState<Year[]>([]),[yearId,setYearId]=useState<number|undefined>(),[events,setEvents]=useState<Event[]>([]),[regs,setRegs]=useState<Reg[]>([]),[stats,setStats]=useState({events:0,registrations:0,schedule_items:0});const [msg,setMsg]=useState('');const [editingYear,setEditingYear]=useState<number|null>(null);const notice=(x:string)=>{setMsg(x);setTimeout(()=>setMsg(''),2500)};
 const load=async()=>{const y=await api('/years');setYears(y);const current=y.find((v:Year)=>v.is_current)||y[0];if(current)setYearId(current.id)}; useEffect(()=>{if(ready)load().catch(()=>setReady(false))},[ready]);useEffect(()=>{if(!yearId)return;Promise.all([api('/events?year_id='+yearId),api('/registrations?year_id='+yearId),api('/dashboard?year_id='+yearId)]).then(([a,b,c])=>{setEvents(a);setRegs(b);setStats(c)})},[yearId]);if(!ready)return <Login done={()=>setReady(true)}/>;
 const createYear=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await api('/years',{method:'POST',body:JSON.stringify({name:f.get('name'),sports_start:f.get('start')||null,sports_end:f.get('end')||null,is_current:true})});await load();notice('学年已创建并设为当前学年')};
 const createEvent=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!yearId)return;const f=new FormData(e.currentTarget);await api('/events?year_id='+yearId,{method:'POST',body:JSON.stringify({name:f.get('name'),grade_group:f.get('grade_group'),gender:f.get('gender'),max_teams:Number(f.get('max_teams')),final_teams:Number(f.get('final_teams')),project_type:f.get('project_type'),description:f.get('description')})});e.currentTarget.reset();setEvents(await api('/events?year_id='+yearId));notice('项目已添加')};
 const createReg=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!yearId)return;const f=new FormData(e.currentTarget);await api('/registrations?year_id='+yearId,{method:'POST',body:JSON.stringify({grade:f.get('grade'),class_name:f.get('class_name'),leader_name:f.get('leader_name'),student_name:f.get('student_name'),gender:f.get('gender'),event_id:Number(f.get('event_id'))||null})});e.currentTarget.reset();setRegs(await api('/registrations?year_id='+yearId));notice('报名已添加')};
 const empty=<div className="empty"><Settings size={28}/><h3>模块准备中</h3><p>该模块的数据结构已纳入学年体系，待项目与报名确认后开放操作。</p></div>;
 let content:React.ReactNode=empty;
 if(page==='概览')content=<><div className="heading"><div><h1>工作台</h1><p>当前学年运动会筹备概况</p></div></div><div className="stats"><Stat label="竞赛项目" n={stats.events} icon={<Trophy/>}/><Stat label="报名学生" n={stats.registrations} icon={<Users/>}/><Stat label="已排赛程" n={stats.schedule_items} icon={<CalendarDays/>}/></div><section className="panel"><h2>工作进度</h2><div className="progress"><span>1</span><b>设置学年</b><i/><span>2</span><b>配置项目</b><i/><span>3</span><b>完成报名</b><i/><span>4</span><b>生成赛程</b></div></section></>;
 const updateYear=async(y:Year)=>{try{await api('/years/'+y.id,{method:'PATCH',body:JSON.stringify({name:y.name.trim(),sports_start:y.sports_start||null,sports_end:y.sports_end||null,is_current:y.is_current})});setEditingYear(null);await load();notice('学年已更新')}catch(e){notice((e as Error).message)}};
 if(page==='学年设置')content=<><Title text="学年设置" sub="每个学年拥有独立的运动会业务数据。"/><section className="panel form"><h2>新建学年</h2><form onSubmit={createYear}><input name="name" placeholder="请输入学年名称" required/><input name="start" type="date"/><input name="end" type="date"/><button><Plus size={16}/>创建并启用</button></form></section><section className="panel"><h2>已有学年</h2><table><thead><tr><th>学年</th><th>运动会时间</th><th>状态</th><th>操作</th></tr></thead><tbody>{years.map(y=><tr key={y.id}><td>{editingYear===y.id?<input value={y.name} onChange={e=>setYears(years.map(v=>v.id===y.id?{...v,name:e.target.value}:v))}/>:y.name}</td><td>{editingYear===y.id?<><input type="date" value={y.sports_start||""} onChange={e=>setYears(years.map(v=>v.id===y.id?{...v,sports_start:e.target.value}:v))}/><input type="date" value={y.sports_end||""} onChange={e=>setYears(years.map(v=>v.id===y.id?{...v,sports_end:e.target.value}:v))}/></>:<>{y.sports_start||"未设置"} {y.sports_end&&"至 "+y.sports_end}</>}</td><td><em className={y.is_current?"active":""}>{y.is_current?"当前学年":"历史学年"}</em></td><td><button className="text" onClick={()=>editingYear===y.id?updateYear(y):setEditingYear(y.id)}>{editingYear===y.id?"保存":"编辑"}</button></td></tr>)}</tbody></table></section></>;
 if(page==='项目管理')content=<><Title text="项目管理" sub="项目名称、组别和性别在当前学年内唯一。"/><section className="panel form"><h2>新增竞赛项目</h2><form onSubmit={createEvent}><input name="name" placeholder="项目名称，如 100米" required/><input name="grade_group" placeholder="组别，如 三年级" required/><select name="gender"><option>男</option><option>女</option><option>混合</option></select><input name="max_teams" type="number" min="0" defaultValue="20"/><input name="final_teams" type="number" min="1" defaultValue="6"/><select name="project_type"><option>个人</option><option>团队</option></select><input name="description" placeholder="项目介绍（可选）"/><button><Plus size={16}/>新增</button></form></section><EventTable rows={events} refresh={async()=>{if(yearId)setEvents(await api('/events?year_id='+yearId))}}/></>;
 if(page==='班级报名')content=<><Title text="班级报名" sub="每个班级限 20 人，男女各不超过 10 人。Excel 导入将在下一轮接入模板校验。"/><section className="panel form"><h2>手动添加报名</h2><form onSubmit={createReg}><input name="grade" placeholder="年级" required/><input name="class_name" placeholder="班级" required/><input name="leader_name" placeholder="领队姓名" required/><input name="student_name" placeholder="学生姓名" required/><select name="gender"><option>男</option><option>女</option></select><select name="event_id"><option value="">暂不选择项目</option>{events.map(x=><option key={x.id} value={x.id}>{x.grade_group} · {x.name} · {x.gender}</option>)}</select><button><Plus size={16}/>添加</button></form></section><section className="panel"><div className="line"><h2>报名名单</h2><button className="secondary" onClick={async()=>{await api('/registrations/generate-bibs?year_id='+yearId,{method:'POST'});setRegs(await api('/registrations?year_id='+yearId));notice('号码已生成')}}>生成号码</button></div><table><thead><tr><th>年级 / 班级</th><th>学生</th><th>性别</th><th>领队</th><th>号码</th></tr></thead><tbody>{regs.map(r=><tr key={r.id}><td>{r.grade} {r.class_name}</td><td>{r.student_name}</td><td>{r.gender}</td><td>{r.leader_name}</td><td>{r.bib_number||'--'}</td></tr>)}</tbody></table></section></>;
 return <div className="shell"><aside><div className="brand"><strong>SFLS</strong><span>运动会系统</span></div><nav>{nav.map(([n,I])=><button key={n} className={page===n?'selected':''} onClick={()=>setPage(n)}><I size={18}/>{n}</button>)}</nav><button className="logout" onClick={()=>{localStorage.removeItem('sfls_token');setReady(false)}}><LogOut size={17}/>退出登录</button></aside><main className="content"><header><div className="year"><CalendarDays size={16}/><select value={yearId||''} onChange={e=>setYearId(Number(e.target.value))}><option value="">选择学年</option>{years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></div><span>管理员</span></header>{yearId||page==='学年设置'?content:<div className="empty"><CalendarDays/><h3>请先创建学年</h3><p>学年是所有运动会数据的基础。</p></div>}{msg&&<div className="toast">{msg}</div>}</main></div>}
function Title({text,sub}:{text:string,sub:string}){return <div className="heading"><h1>{text}</h1><p>{sub}</p></div>}; function Stat({label,n,icon}:{label:string,n:number,icon:React.ReactNode}){return <section className="stat"><div>{icon}</div><p>{label}</p><strong>{n}</strong></section>};function EventTable({rows,refresh}:{rows:Event[],refresh:()=>Promise<void>}){return <section className="panel"><h2>竞赛项目清单</h2><table><thead><tr><th>项目</th><th>组别</th><th>性别</th><th>类别</th><th>上限 / 决赛</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.grade_group}</td><td>{x.gender}</td><td>{x.project_type}</td><td>{x.max_teams} / {x.final_teams}</td><td><button className="text" onClick={async()=>{await api('/events/'+x.id,{method:'DELETE'});refresh()}}>删除</button></td></tr>)}</tbody></table></section>}; createRoot(document.getElementById('root')!).render(<App/>);
